### PR TITLE
Fix memory leak of malloc-ed memory

### PR DESCRIPTION
**Pull request by pjongy**
#115 

- Replace Tensor.ctensor type from Ctensor to *Ctensor
- Apply malloccedCtensor flag to verify ctensor allocated by malloc or AtXXX

### CODE REVIEW

**Comment by pjongy** [comment]
I temporarily defined mock function to `tensor-generated.go` for test like this.

For this code with (un)comment the part of `C.free(~)` we can check if lack of explicit free to malloc-ed memory causes memory leak.
(C.free should be called with `*lib.Ctensor` and this is why my PR refactors the part of ctensor as pointer structure of `ts.Tensor`)
```
func MemoryTestWithRand(size []int64, optionsKind gotch.DType, optionsDevice gotch.Device) { 
  ptr := (*lib.Ctensor)(unsafe.Pointer(C.malloc(0)))

  sizeLen := len(size)
  lib.AtgRand(ptr, size, sizeLen, optionsKind.CInt(), optionsDevice.CInt())
  if err := TorchErr(); err != nil {
    err = fmt.Errorf("Permute() failed: %w", err)
  }
  lib.AtFree(*ptr)
  //C.free(unsafe.Pointer(ptr))  // If not free this pointer, memory leaks
}
```


Here is the test code. (in CPU gotch env)
```
package main

import (
        "fmt"
        "sync"

        "github.com/sugarme/gotch"
        "github.com/sugarme/gotch/ts"
)


func main() {
        wg := &sync.WaitGroup{}
        wg.Add(1)
        for j :=0; j< 10; j++ {
                wg.Add(1)
                go func(kk int) {
                        for i := 0; i < 100000; i++ {
                                if i % 1000 == 0 {
                                        fmt.Printf("ran(%d): %d\n", kk, i)
                                }
                                ts.MemoryTestWithRand([]int64{3, 3, 3}, gotch.Float, gotch.CPU)
                        }
                        wg.Done()
                }(j)
        }
        wg.Wait()
}
```

Then we can get residen memory growing up (refresh term of `top` I set is 0.1 second (by input "d" -> "0.1" -> "enter"))
You just need to see "RES" column
```
                                    * <-  Just need to see here
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   3937 root      20   0  385848  43584  28032 R  30.0   0.1   0:00.03 aaa.com
   3937 root      20   0 2009032  99724  53184 S 190.0   0.3   0:00.22 aaa.com
   3937 root      20   0 2306356 111196  53184 S 740.0   0.3   0:00.96 aaa.com
   3937 root      20   0 2380088 119808  53184 S 770.0   0.4   0:01.73 aaa.com  <- memory growing up by create new tensor with malloc(0)
   3937 root      20   0 2380088 127596  53184 S 750.0   0.4   0:02.48 aaa.com
   3937 root      20   0 2380484 135192  53184 S 680.0   0.4   0:03.16 aaa.com
   3937 root      20   0 2380484 135192  53184 S  10.0   0.4   0:03.17 aaa.com  <- memory does not released even if cpu util going 0 (all task done timing)
   3937 root      20   0 2380484 135192  53184 S   0.0   0.4   0:03.17 aaa.com
```

And here is memory status when uncomment free part:
```
func MemoryTestWithRand(size []int64, optionsKind gotch.DType, optionsDevice gotch.Device) { 
  ptr := (*lib.Ctensor)(unsafe.Pointer(C.malloc(0)))

  sizeLen := len(size)
  lib.AtgRand(ptr, size, sizeLen, optionsKind.CInt(), optionsDevice.CInt())
  if err := TorchErr(); err != nil {
    err = fmt.Errorf("Permute() failed: %w", err)
  }
  lib.AtFree(*ptr)
  C.free(unsafe.Pointer(ptr))  // If not free this pointer, memory leaks
}
```

```
                                    * <-  Just need to see here
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   3538 root      20   0  401516  63728  32448 R  80.0   0.2   0:00.08 aaa.com
   3538 root      20   0 2231440 101744  53376 R 490.0   0.3   0:00.57 aaa.com
   3538 root      20   0 2379224 103088  53376 R 750.0   0.3   0:01.32 aaa.com
   3538 root      20   0 2379224 102636  53376 R 750.0   0.3   0:02.07 aaa.com  <- memory does not growing up by create new tensor with malloc(0) (because of explicit free)
   3538 root      20   0 2527200 102772  53376 S 750.0   0.3   0:02.82 aaa.com
   3538 root      20   0 2527200 102748  53376 S 480.0   0.3   0:03.30 aaa.com
   3538 root      20   0 2527200 102748  53376 S   0.0   0.3   0:03.30 aaa.com  <- most of memory released when cpu util going 0 (all task done timing)
```


This means we should free explicitly to allocated by malloc(0)
But non-malloc-ed tensor memory exists like:
(ts/jit.go)
```
        case 1:
                tensor := lib.AtiToTensor(cval.civalue)
                if err := TorchErr(); err != nil {
                        return nil, err
                }
                return &IValue{
                        value: newTensor(&tensor),
                        kind:  TensorVal,
                        name:  "Tensor",
                }, nil
```
If we try `C.free` to this `tensor`, double free abort will be occurred. (and this is why `ts.malloccedCtensor` is needed)

**Comment by pjongy** [comment]
I totally understand your comment (that GOGC can sweep uintptr and could be make side effects about pre-drop-free-ed pointer) https://github.com/sugarme/gotch/pull/114/files#r1369249595

So @sugarme ,
Could you review this PR once more time?

ps. Changing `ts.Tensor.ctensor` as pointer is quite confusing in jit.go ... etc but I think this is better way than #114 or present (unfree malloc)

**Comment by pjongy** [comment]
Furthermore, I've tested some test codes by `go test ./ts` but it raises error because of no CUDA.
I think this PR should be tested on both CPU and CUDA. if you think it's gonna be work, could you check this?

**Comment by sugarme** [comment]
@pjongy ,

Thanks again for spending time on this.

I just wanted to clarify that gotch `ts.Tensor` is a Go construct that holds C pointer to `torch::Tensor`:

```go
type Tensor struct{
    ctensor lib.Ctensor // <-- lib.Ctensor is C pointer to torch::Tensor (ctensor = torch::Tensor*)
}
```
What you are trying to change is gotch `ts.Tensor` holds **a pointer to a pointer** to `torch::Tensor`? This may change fundamentally how to build a Go binding to C with `unsafe.Pointer`. I think I used double pointer once somewhere to deal with callback function. I am not sure what it can be with "double pointer" here. May be you can create a branch and play with this for a while to see how it is going before go further. 
Do you know that we can do *training* with gotch as well? Need to explore this aspect as well, make sure autograd system working as well.

**Comment by pjongy** [comment]
Yes @sugarme , ts.Tensor to be hold **pointer of pointer** . 
But what I've changed is not exact usage of n depth pointer you think (like n-d aray or function pointer for callback ...etc) but is just to make able to run `C.free` about `ts.Tensor.ctensor` (I couldn't run C.free on ts.Ctensor as **just 1 depth pointer** ).
It's okay to not to change ts.Tensor.ctensor data type if there is more graceful way to free this.

I didn't use gotch as traing yet, can you give me some tutorial links or steps for test propagate grad? (or could you test grad codes with this change by your hand if it's okay?)

**Comment by sugarme** [comment]
@pjongy ,

I have not intend to change this and as mentioned before, there is no issue at all and not a priority for now as I want to work toward stable APIs. 

If you want to play with `gotch` there quite a few things to play in `example` folder. Feel free to open a discussion in the discussion folder. 

I will close this PR for now. Ta.

**Comment by pjongy** [comment]
I see. thank you :)

**Comment by sugarme** [comment]
@pjongy ,

in gotch, tensors will be cleaned up in 2 ways (hybrid): 
1. Manually, if you are sure you don't need, you can free up tensors immediately by calling `.MustDrop()` method (It's very memory efficient)
2. Delegate to Go Garbage Collection (by default when a tensor is created, it is already setup for GC [runtime.SetFinalizer](https://github.com/sugarme/gotch/blob/05eb7f538b3b10d4e78f0b11f58c827750de69a9/ts/tensor.go#L87). And Go will do the job for you at its convenient time (that why you will see your computer RAM fluctuation but in a stable condition for a long run) in general.  In practice, it's not really so - depending on C memory allocation side and so on, but that's other story. 

Hope that helps.

**Pull request closed without merging**
