### PR TITLE
Can now build using build tags

### PR DESCRIPTION
**Pull request by oliverdain**
Updated the README with the updated instructions. I don't have a GPU to test the GPU build but I was able to link against the GPU version of libtorch and all tests except that one that actually requires a GPU passed which indicates it all works.

### CODE REVIEW

**Comment by sugarme** [comment]
@oliverdain,

Thanks for your PR. I have a quick look at the build tag and wonder how you solve the case where I have in my code:

`device=gotch.CPU` while specify build tag with `gotch-cpu` and vice versa? I have libtorch CPU installed and build tag `gotch-gpu` and in my code I specify my tensor in CPU only?

**Comment by oliverdain** [comment]
@sugarme you can still put tensors on the CPU if you build with build tag `gotch-gpu`. And you can put tensors on the CPU if you build without that tag. Of course you can not put tensors on the GPU if you don't build with `gotch-gpu` as you've compiled without GPU support.

Note that the vast majority of your unit tests run with tensors on the CPU and those tests pass when run with `-tags=gotch-gpu`.

Before this PR if you wanted to build with GPU support you ran a script with the right environment variables set. That script that modified `lib.go`  with various cgo directives to link against CUDA libs, etc. With this PR there's two versions of `lib.go`. `libcpu.go` is identical to what your script used to produce when you ran it with `CUDA_VER=cpu` and `libgpu.go` is identical to what that script used to produce when you ran it with `CUDA_VER=11.8`. The build tags ensure that only 1 of those two files is used. So if you build with `-tags=gotch_gpu` it'll ignore `libcpu.go` and use `libgpu.go`. The result is exactly the same as if you'd run the `setup-gotch.sh` script with `CUDA_VER=11.8` set in your environment.

**Comment by sugarme** [comment]
@oliverdain,

Thanks. 

Supposing I am a new gotch user and here are steps I am going to take to run a "hello-world" program using gotch:

## My computer has no GPU

1. Install libtorch library for CPU

```
    wget https://github.com/sugarme/gotch/releases/download/v0.9.0/setup-libtorch.sh
    chmod +x setup-libtorch.sh
    export CUDA_VER=cpu && bash setup-libtorch.sh
```

3. `helloworld` program

```bash
mkdir hello-gotch && cd hello-gotch
go mod init "github.com/AWESOME_DEV/hello-gotch.git"
go get github.com/sugarme/gotch@v0.9.1
go mod tidy  # <--- what going on here??? (what build tag it takes to link libtorch)
```

create `main.go` with the following code:

```go
import (
	"fmt"

	"github.com/sugarme/gotch"
	"github.com/sugarme/gotch/ts"
)

func main(){
    device := gotch.CudaIfAvailable()
    x := ts.MustOfSlice([]float64{1, 2, 3, 4, 5, 6})
    x = x.MustView([]int64{2, 3})
    x = x.MustTo(device)

    fmt.Printf("x tensor: %i\n, x)
}

```

5. Run

```bash
go run .  # What build tag it takes? 
```

7. Build

```bash
go build -tags=gotch_cpu . # success

go build -tags=gotch_gpu . # fail? 


# A reminder that this product is built with libtorch CPU and would need libtorch CPU setup at the target deployment box. 
```


## My computer has Nvidia GPU

1. Install Nvidia GPU driver, CUDA and CuDNN libraries

[Install nvidia driver here](https://www.nvidia.com/Download/Find.aspx?lang=en)
[Install CUDA here](https://developer.nvidia.com/cuda-downloads)
[Install CuDNN here](https://developer.nvidia.com/rdp/cudnn-download#)

3. Install libtorch library for CUDA

```bash
    wget https://github.com/sugarme/gotch/releases/download/v0.9.0/setup-libtorch.sh
    chmod +x setup-libtorch.sh

    export CUDA_VER=11.8 && bash setup-libtorch.sh
```

5. `helloworld` program

```bash
mkdir hello-gotch && cd hello-gotch
go mod init "github.com/AWESOME_DEV/hello-gotch.git"
go get github.com/sugarme/gotch@v0.9.1
go mod tidy  # <--- what going on here??? (what build tag it takes to link libtorch)
```

create `main.go` with the following code:

```go
import (
	"fmt"

	"github.com/sugarme/gotch"
	"github.com/sugarme/gotch/ts"
)

func main(){
    device := gotch.CudaIfAvailable()
    x := ts.MustOfSlice([]float64{1, 2, 3, 4, 5, 6})
    x = x.MustView([]int64{2, 3})
    x = x.MustTo(device)

    fmt.Printf("x tensor: %i\n, x)
}

```


6. Run

```bash
go run .  # What build tag it takes? Default is !gotch_gpu?
```

7. Build

```bash
go build -tags=gotch_cpu . # fail?

go build -tags=gotch_gpu . # success? 


# the built product will be deployed to box with libtorch for GPU installed only. 
```

Some guessing points I want to make here:
-  Instead of run `go mod tidy` we would need to run `go build tags=...` first with corresponding libtorch to link gotch and libtorch. Then `go run . ` as many as needed with the already built and linked gotch. 
-  If you want to deploy to various box with different hardware, you need libtorch for such hardware.
- If we upgrade gotch version, we need to run `go clean && go clean -cache` then `go build -tags=...` to rebuild gotch. Then `go run . ` as normal. 


Would you mind to check the CPU part to see anything unexpected? 
I would need to set up a clean box to test GPU part.

We also need to update `installation` guide as such. 

Many thanks. Will merge PR here. Will make it way to the master when all tested. 

Cheers,

**Comment by oliverdain** [comment]
# High Level

Build tags are only relevant to steps that build (like `run`, `build`, and `test`). So you do not specify a build tag for things like `go mod tidy` which don't build anything. Indeed, `go mod tidy` updates `go.mod` and `go.sum` to say which libraries your project depends on but not how they should be built and that's a good thing: it means you can share your project with people who do and do not have GPUs.

The CPU-only version is the default so when building for CPU no build tag is specified. You only specify a build tag if you need GPU support.

# Specifics

## My computer has no GPU
1. Install libtorch library for CPU
```
    wget https://github.com/sugarme/gotch/releases/download/v0.9.0/setup-libtorch.sh
    chmod +x setup-libtorch.sh
    export CUDA_VER=cpu && bash setup-libtorch.sh
```

2. `helloworld` program

```
mkdir hello-gotch && cd hello-gotch
go mod init "github.com/AWESOME_DEV/hello-gotch.git"
go get github.com/sugarme/gotch@v0.9.1

# No build tag needed. This isn't a build step. Also, it's too soon to run "go mod tidy" here because your code doesn't
# yet depend on gotch so go mod tidy will correctly not add it to go.mod. This has nothing to do with build tags
# That's how go mod tidy works for any library.
go mod tidy
```

create main.go with the following code:

```
import (
	"fmt"

	"github.com/sugarme/gotch"
	"github.com/sugarme/gotch/ts"
)

func main(){
    device := gotch.CudaIfAvailable()
    x := ts.MustOfSlice([]float64{1, 2, 3, 4, 5, 6})
    x = x.MustView([]int64{2, 3})
    x = x.MustTo(device)

    fmt.Printf("x tensor: %i\n, x)
}
```

No you need to run `go mod tidy` because now your code depends on `gotch`. This is how `go mod tidy` works with any library: it looks at your code, sees what it uses and doesn't use and updates `go.mod` and `go.sum` accordingly. This isn't a build step so no build tag needed.

```
go mod tidy
```

Run

```
# no build tag needed as CPU is the default
go run .
```

Build
```
# No build tag needed. CPU is the default
go build . # success
```

```
# This will fail as you don't have CUDA stuff setup so it will fail to link.  The errors you'll
# get are exactly the same as the errors you'd get if you run setup-gotch.sh with the CUDA env
# variable set but you didn't actually have the CUDA libraries installed.
go build -tags=gotch_gpu .
```
# A reminder that this product is built with libtorch CPU and would need libtorch CPU setup at the target deployment box. 

## My computer has Nvidia GPU

1. Install Nvidia GPU driver, CUDA and CuDNN libraries
[Install nvidia driver here](https://www.nvidia.com/Download/Find.aspx?lang=en)
[Install CUDA here](https://developer.nvidia.com/cuda-downloads)
[Install CuDNN here](https://developer.nvidia.com/rdp/cudnn-download#)

Install libtorch library for CUDA
```
    wget https://github.com/sugarme/gotch/releases/download/v0.9.0/setup-libtorch.sh
    chmod +x setup-libtorch.sh

    export CUDA_VER=11.8 && bash setup-libtorch.sh
```

2. `helloworld` program

```
mkdir hello-gotch && cd hello-gotch
go mod init "github.com/AWESOME_DEV/hello-gotch.git"
go get github.com/sugarme/gotch@v0.9.1
```
create main.go with the following code:

```
import (
	"fmt"

	"github.com/sugarme/gotch"
	"github.com/sugarme/gotch/ts"
)

func main(){
    device := gotch.CudaIfAvailable()
    x := ts.MustOfSlice([]float64{1, 2, 3, 4, 5, 6})
    x = x.MustView([]int64{2, 3})
    x = x.MustTo(device)

    fmt.Printf("x tensor: %i\n, x)
}
```

3. Run

```
# No build tag needed as tidy isn't a build step
go mod tidy

# This will build without GPU support and run just fine but it won't use the GPU
# because you didn't give the gotch_gpu build tag so it'll build without GPU support
go run . 

# This will build with GPU support and therefore the CudaIfAvailable() call will
# return a CUDA device and it'll run on the GPU
go run -tags=gotch_gpu .
```

4. Build
```
# Default CPU-only build. This will succeed but you won't have GPU support even though a GPU
# is available. This is the same as if you'd run your setup-gotch.sh script with CUDA=cpu env variable
# set even though your machine had a GPU
go build . 

# This will build with GPU support
go build -tags=gotch_gpu .
```


# Q & A

> Instead of run go mod tidy we would need to run go build tags=... first with corresponding libtorch to link gotch and libtorch. Then go run .  as many as needed with the already built and linked gotch.

No. `go mod tidy` just says you depend on `gotch` but it doesn't specify how to build it. That is a good thing. For example, imagine you and I are collaboring on an executable that uses `gotch` and I have a GPU and you don't. I can pull the git repo and build with `-tags=gotch_gpu` and run things on my GPU while you can work in the same repo, with the same `go.mod` and `go.sum` but you build without any build tags and things run on your CPU-only machine just fine.

> If you want to deploy to various box with different hardware, you need libtorch for such hardware.

Correct. That was true before this change too though.

> If we upgrade gotch version, we need to run go clean && go clean -cache then go build -tags=... to rebuild gotch. Then go run .  as normal.

I'm not sure. The Go bug where you have to clean has to do with changes to `cgo` code that go doesn't detect. Upgrading versions might be OK - I think Go would know that the library version has changed and that invalidates the cache. But I'm not sure. If you do need to do a `go clean` that has nothing to do with a change to using build tags; that bug would have the same effect if you were building things with your `setup-gotch.sh` script.

Note that with the old scripts if I'd installed `gotch` with `setup-gotch.sh` with `CUDA=cpu` and I then re-ran `setup-gotch.sh` with `CUDA=11.8` I'd also have to do a `go clean`.

> Would you mind to check the CPU part to see anything unexpected?

I already did. All your unit tests pass.

> I would need to set up a clean box to test GPU part.

That'd be great.

> We also need to update installation guide as such.

I think this PR includes the changes to the README. Did I miss something?

**Comment by oliverdain** [comment]
@sugarme wondering if you've had a chance to read my response and/or to test out on a GPU machine. If you haven't had time to test I could spin up a GPU instance in the cloud and test if that'd be helpful.

**Comment by sugarme** [comment]
@oliverdain,

Would be great if you could. Thanks. 
I have to spin up to test myself anyway. 
Cheers.

**Pull request merged**
